name: lnmarkets_bot
description: LN Markets Trend Tabajara 3.0 Bot
publish_to: 'none'
version: 3.3.1+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_foreground_task: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A0E00"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_monochrome: "assets/icon/icon.png"
  web:
    generate: false
  windows:
    generate: false

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
